AUGMENTATION: true
BATCH_SIZE: 16
BEST_MAX_SENT_LENGTH: 74
BEST_VOCAB_SIZE: 18316
EPOCHS: 10
IMAGE_SIZE: 224
INCLUDE_TOP: false
MAX_SENT_LENGTH: 29
SPLIT_RATIO: 0.9
VOCAB_SIZE: 2817
WEIGHTS: imagenet
X_COL: image
Y_COL: caption
