AUGMENTATION: true
BATCH_SIZE: 16
EPOCHS: 2
IMAGE_SIZE: 224
INCLUDE_TOP: false
MAX_SENT_LENGTH: 29
MY_MAX_SENT_LENGTH: 74
MY_VOCAB_SIZE: 18316
SPLIT_RATIO: 0.9
VOCAB_SIZE: 2817
WEIGHTS: imagenet
X_COL: image
Y_COL: caption
