artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  mongo_uri: MONGO_URI
  image_data_folder: artifacts/data_ingestion/Images
  csv_file_path: artifacts/data_ingestion/captions.csv

data_validation:
  root_dir: artifacts/data_validation
  image_data_folder: artifacts/data_ingestion/Images
  csv_file_path: artifacts/data_ingestion/captions.csv
  train_data_path: artifacts/data_validation/train_data.csv
  validation_data_path: artifacts/data_validation/validation_data.csv
  bad_images_data_path: artifacts/data_validation/bad_images.txt

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  dense_model_path: artifacts/prepare_base_model/dense_model.h5 #densenet201
  main_model_path: artifacts/prepare_base_model/main_model.h5 #end train model
  image_feature_json_path: artifacts/prepare_base_model/image_feature.json #contain image feature from densenet
  captions_csv_file_path: artifacts/data_ingestion/captions.csv
  image_data_folder: artifacts/data_ingestion/Images
  tokerizer_path: artifacts/prepare_base_model/tokerizer.pkl
  model_image_path: artifacts/prepare_base_model/model_image.png