artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  mongo_uri: MONGO_URI
  image_data_folder: artifacts/data_ingestion/Images
  csv_file_path: artifacts/data_ingestion/captions.csv
