artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  mongo_uri: MONGO_URI
  image_data_folder: artifacts/data_ingestion/Images
  csv_file_path: artifacts/data_ingestion/captions.csv

data_validation:
  root_dir: artifacts/data_validation
  image_data_folder: artifacts/data_ingestion/Images
  csv_file_path: artifacts/data_ingestion/captions.csv
  train_data_path: artifacts/data_validation/train_data.csv
  validation_data_path: artifacts/data_validation/validation_data.csv
  bad_images_data_path: artifacts/data_validation/bad_images.txt

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5 #densenet201
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 #end train model